### ISSUE TITLE
How to join ONNX?

### ISSUE THREAD

**Issue by shashichilappagari** [onnx/steering-committee#2]
Hi,
I am co-founder of DeGirum corp. We are a startup working on building HW accelerators for ML inference. We use ONNX for our development. We wanted to know how our company can join ONNX.

**Comment by prasanthpul** [comment]
Thanks for reaching out. ONNX is open source so you can start participating via GitHub, Gitter, and the Working Groups and SIGs. Take a look at https://github.com/onnx/onnx/blob/master/community/ for more info. We are also working on guidelines for being a Member Company which gets your logo on the website. We also have periodic workshops.

**Comment by shashichilappagari** [comment]
Prasanth,
Thanks for the information. From time-to-time, we see announcements saying so-and-so company joined ONNX. So, I was under the impression that there is some official way of becoming an ONNX member. It now appears that the guidelines are still being worked on. We will wait for these to be finalized. 
One aspect that we are interested in is the support for sparsity in ONNX. We are building custom HW that can provide significant gains when using pruned networks. We have not seen a working group for this purpose. We will soon submit a proposal  via PR for this feature with the information mentioned in the guidelines.
Regards
Shashi

**Comment by prasanthpul** [comment]
Take a look at this PR: https://github.com/onnx/onnx/pull/2019

**Comment by shashichilappagari** [comment]
Thanks Prasanth. This is very useful for us.

**Comment by prasanthpul** [comment]
Process for getting logo posted has been published: https://github.com/onnx/onnx/blob/master/community/logo_request.md
