### ISSUE TITLE
Update ONNX Repositories for License Change

### ISSUE THREAD

**Issue by szha** [onnx/steering-committee#43]
Now that we adopt Apache License v2.0 in favor of MIT license, we need to update the licenses for these repositories in the onnx org:
- [ ] sklearn-onnx
- [ ] onnx-mlir
- [ ] steering-committee
- [ ] tensorflow-onnx
- [ ] backend-scoreboard
- [ ] optimizer
- [ ] onnx-tensorrt
- [ ] onnx (onnx/onnx#3159)
- [ ] models
- [ ] onnx-tensorflow
- [ ] keras-onnx
- [ ] onnxmltools
- [ ] sigs
- [ ] onnx-docker
- [ ] working-groups
- [ ] onnx.github.io
- [ ] wheel-builder
- [ ] tutorials
- [ ] onnx-r
- [ ] onnx-coreml

**Comment by prasanthpul** [comment]
all active ones should have been updated. if not, please open separate issues on those repos.
