### ISSUE TITLE
Volunteer to be a maintainer/approver

### ISSUE THREAD

**Issue by daquexian** [onnx/steering-committee#64]
Hi Steering Committee,

I'm daquexian, an active [contributor](https://github.com/onnx/onnx/pulls?q=is%3Apr+author%3Adaquexian+is%3Aclosed) to ONNX project, the member of infra and operator SIG (thanks for the invitation of @linkerzhang ), the maintainer of [onnx optimizer](https://github.com/onnx/optimizer), the author of the popular [onnx simplifier](https://github.com/daquexian/onnx-simplifier), and I have also given two presentations in onnx community meetup.

ONNX is so widely-used that there are many community contributors submitting PRs, however, some PRs cannot get reviews and be merged in a sensible time due to the lack of reviewers, for example, https://github.com/onnx/onnx/pull/4285 which is only a 1-line change. In the [meeting note](https://github.com/onnx/steering-committee/blob/main/meeting-notes/20220622.md#help-with-onnx-pr-monitoring), I noticed that the Steering Committee wants to encourage more people to be maintainers/approvers for managing PRs, and I'm also looking forward to having a chance to help ONNX be better. So I volunteer to be a maintainer/approver and help review PRs about infra and operator. I would appreciate it greatly if I can have the chance.

Thanks!

**Comment by linkerzhang** [comment]
Adding committee members 

@prasanthpul @AlexandreEichenberger @mk-nvidia @rajeevnalawadi  @Andreas Fehlner

**Comment by prasanthpul** [comment]
Thank you @daquexian!

Tagging the SIG leads (@gramalingam, @postrational, @liqunfu, @linkerzhang) so they can get you involved with reviewing PRs.

**Comment by andife** [comment]
Many thanks for the support!
[already added to https://github.com/onnx/sigs/blob/main/CONTRIBUTORS]
