### ISSUE TITLE
VFX Virtual Production tool for Unreal Engine

### ISSUE THREAD

**Issue by albertotrunk** [onnx/steering-committee#71]
Hi Steering Committee! 
I'm making a new VFX Virtual Production/games tool for Unreal Engine, Dream

I text this in a hurry due I just saw the following twitt:
https://twitter.com/onnxai/status/1600603167489929217?s=20&t=tEJh6GZP6TjWEhhNt6EjgQ

I was wondering what I can do with ONNX in unreal after training a model with the videogame "self iterating":

![image](https://user-images.githubusercontent.com/8300565/216982493-b367ca3b-24ea-47df-b8a6-d3e061a2dd53.png)

Dream is a plug-in made to improve the workflows and quality of the users independently of their expertise.
A better user experience improves Unreal Engine as an all-in-one tool, 
from the prototype until the final art with photorealistic generations never seen before.

https://www.youtube.com/watch?v=kEiDWhktLao

It is in my roadmap currently experimenting with ONNX,
feel free to contact me :)

Alberto Cerdá Estarelles
![image](https://user-images.githubusercontent.com/8300565/216983584-d534c4e4-c4bf-4e29-819a-f39fa567c876.png)

Discord: AlbertoTrunk#7305
LinkedIn: https://www.linkedin.com/in/albertocerdaestarelles/

**Comment by prasanthpul** [comment]
The Unreal Engine has integrated with ONNX Runtime. Check this video https://www.youtube.com/watch?v=oWYphpV6A40& and ask any further questions in the https://github.com/microsoft/onnxruntime repo

**Comment by albertotrunk** [comment]
Yeah... that's why I'm here, nothing similar... but I'll try to use as base
...
